version: '3'

services:
  prosody:
    image: prosody/prosody:latest
    container_name: prosody
    ports:
      - "5222:5222"    # XMPP client port
      - "5280:5280"    # HTTP web admin (optional)
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
      - prosody_data:/var/lib/prosody
    environment:
      - XMPP_DOMAIN=localhost

volumes:
  prosody_data:
